"""System prompts for the scheduling agent."""

from .system import (
    SCHEDULING_AGENT_SYSTEM_PROMPT,
    GREETING_TEMPLATE,
    VERIFICATION_PROMPT,
    APPOINTMENT_CONFIRMATION_TEMPLATE,
    BOOKING_CONFIRMATION_TEMPLATE,
    CLOSING_TEMPLATE,
)

__all__ = [
    "SCHEDULING_AGENT_SYSTEM_PROMPT",
    "GREETING_TEMPLATE",
    "VERIFICATION_PROMPT",
    "APPOINTMENT_CONFIRMATION_TEMPLATE",
    "BOOKING_CONFIRMATION_TEMPLATE",
    "CLOSING_TEMPLATE",
]
